version: '3'
services:
  discovery-srv:
    container_name: discovery-srv
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: eureka-image:latest
    ports:
      - 8761:8761
    networks:
      - docker-network

  booking-srv:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    image: booking-image:latest
    ports:
      - 8081:8081
    networks:
      - docker-network
    links:
      - discovery-srv
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-srv:8761/eureka

  order-srv:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-image:latest
    ports:
      - 8082:8082
    networks:
      - docker-network
    links:
      - discovery-srv
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-srv:8761/eureka

networks:
  docker-network:
    driver: bridge


